name: covid_app
dependencies:
- brotlipy=0.7.0
- certifi=2020.6.20
- cffi
- click=7.1.2
- dash
- dash-core-components
- dash-html-components
- dash-renderer
- dash-table
- Flask=1.1.2
- Flask-Compress=1.5.0
- future=0.18.2
- itsdangerous=1.1.0
- Jinja2=2.11.2
- MarkupSafe=1.1.1
- numpy
- pandas
- pip
- plotly
- pycparser
- python-dateutil=2.8.1
- pytz=2020.1
- PyYAML=5.3.1
- retrying=1.3.3
- six
- Werkzeug=1.0.1
- wincertstore=0.2
- pip:
  - gunicorn==20.0.4
